### ISSUE TITLE
error starting up goldenenchants*

### ISSUE THREAD

**Issue by cr0wm4n1** [nulli0n/GoldenEnchants#14]
[20:27:02 WARN]: Enabled plugin with unregistered PluginClassLoader GoldenEnchants v2.10.1
[20:27:03 WARN]: [GoldenEnchants] ============== DISCLAIMER ==============
[20:27:03 WARN]: [GoldenEnchants] > You're running an unknown Spigot fork.
[20:27:03 WARN]: [GoldenEnchants] > This plugin is designed to work on Spigot (spigotmc.org) only!
[20:27:03 WARN]: [GoldenEnchants] > You won't get any support for any issues unless they persist on regular Spigot.
[20:27:03 WARN]: [GoldenEnchants] ========================================
[20:27:03 INFO]: [GoldenEnchants] Powered by: NexEngine
[20:27:03 INFO]: [GoldenEnchants] Tiers Loaded: 5
[20:27:03 ERROR]: Error occurred while enabling GoldenEnchants v2.10.1 (Is it up to date?)
java.lang.NoSuchMethodError: su.nexmedia.engine.core.config.CoreLang: method 'void <init>(su.nexmedia.engine.NexPlugin)' not found
        at su.nightexpress.goldenenchants.config.Lang.<init>(Lang.java:12) ~[?:?]
        at su.nightexpress.goldenenchants.GoldenEnchants.setConfig(GoldenEnchants.java:78) ~[?:?]
        at su.nexmedia.engine.config.ConfigManager.setup(ConfigManager.java:32) ~[?:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:168) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:88) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
        at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:124) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2091) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1902) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1855) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at java.lang.Thread.run(Unknown Source) [?:?]
        
I have nexengine. I used the exact plugin on my hub to test it and it worked but it wont work on another server

**Comment by cr0wm4n1** [comment]
Do i have to have spigot

**Comment by cr0wm4n1** [comment]
Now golden crates is broken it worked before I added this plugin 
[21:51:52 ERROR]: Could not pass event InventoryClickEvent to GoldenCrates v3.10.0
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.getEntry0(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at su.nexmedia.engine.manager.api.gui.NGUI.click(NGUI.java:427) ~[?:?]
        at su.nexmedia.engine.manager.api.gui.NGUI.onEventClick(NGUI.java:461) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor742.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2610) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by cr0wm4n1** [comment]
Either goldencrates works or goldenenchants works they both cant run at the same time

**Comment by cr0wm4n1** [comment]
[22:27:53] [Server thread/ERROR]: Error occurred while enabling GoldenCrates v3.10.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'void su.nexmedia.engine.config.api.ILangTemplate.<init>(su.nexmedia.engine.NexPlugin)'
	at su.nightexpress.goldencrates.config.Lang.<init>(Lang.java:12) ~[?:?]
	at su.nightexpress.goldencrates.GoldenCrates.setConfig(GoldenCrates.java:105) ~[?:?]
	at su.nexmedia.engine.config.ConfigManager.setup(ConfigManager.java:32) ~[?:?]
	at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:164) ~[?:?]
	at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:938) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"7734ef0"]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by cr0wm4n1** [comment]
I can't run on spigot without iron golem spawners breaking

**Comment by nulli0n** [comment]
use both .jar
